import Foundation
import Testing

/// Synthetic media generated by scripts/make-test-media.sh.
enum Media {
    static func url(_ name: String) throws -> URL {
        try #require(Bundle.module.url(forResource: name, withExtension: nil, subdirectory: "Fixtures"))
    }

    /// The 3 s 320×180 test pattern with its separate 3 s tone, like a DASH video and audio pair.
    static func clip() throws -> PlayableStreamFixture {
        PlayableStreamFixture(video: try url("test-video-only.mp4"), audio: try url("test-tone.m4a"))
    }
}

struct PlayableStreamFixture {
    let video: URL
    let audio: URL
}
